# This is a basic workflow to help you get started with Actions

name: Update README

permissions:
  contents: write
  pull-requests: write  

# Controls when the workflow will run
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out current commit

      - name: Generate new README.md
        run: python ./.github/workflows/updateReadme.py
        
      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit
        if: steps.verify_diff.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "auto generate README.md"
          git push

